### ISSUE TITLE
Verificar se assijus está fechando arquivos abertos

### ISSUE THREAD

**Issue by Markenson** [assijus/assijus#1]
Ao clicar no link que faz o download do assijus.exe ocorre o erro abaixo.

![image](https://cloud.githubusercontent.com/assets/2985140/15979462/7b0d103e-2f3a-11e6-85d5-8d85c197138d.png)
![image](https://cloud.githubusercontent.com/assets/2985140/15979472/8c24060c-2f3a-11e6-8b08-17e10c5470ef.png)

Provavelmente o sistema não está fechando os arquivos abertos

**Comment by Markenson** [comment]
Segundo @raphaelpaiva o problema está ocorrendo com o ulimit da máquina.

@crivano sugeriu verificar se a rotina que responde o JSON e a que lê o arquivo swagger.yaml está deixando algo aberto.

**Comment by crivano** [comment]
Resolvido por @Markenson no swagger-servlet
