### ISSUE TITLE
Apenas documentos marcados "Como subscritor" são listados para assinatura

### ISSUE THREAD

**Issue by Markenson** [assijus/assijus#11]
Reportado por Martellet, via e-mail (quarta-feira, 22 de junho de 2016 15:59) que os anexos não estavam aparecendo para assinatura. O @crivano informou que apenas os documentos "Como subscritor" estão sendo listados.

**Comment by Markenson** [comment]
O mesmo problema ocorre quando uma pessoa é cossignatária. Apenas o subscritor vê o documento na lista

**Comment by crivano** [comment]
Corrigido aqui: https://github.com/projeto-siga/siga/commit/89e371003797bb864edc6162dcf3d24638a52418
