### ISSUE TITLE
Melhorar a mensagem de erro quando não acha o token

### ISSUE THREAD

**Issue by raphaelpaiva** [assijus/assijus#2]
A mensagem abaixo é um pouco intimidadora. O que acham de trocar "Problema - geral" por "Erro" ou "Atenção" e colocar uma instrução pro usuário? Por exemplo:

"Atenção: Nenhum certificado encontrado. Tenha certeza de que o token está encaixado no computador e o assijus.exe (com link) está rodando."

![image](https://cloud.githubusercontent.com/assets/485947/15979646/b3a2e2a6-2f3b-11e6-800c-50e9933c12bd.png)

**Comment by crivano** [comment]
Olá, esse erro só ocorre quando o Assijus já está rodando e operando
normalmente. Abs

Em sex, 10 de jun de 2016 18:49, Raphael Paiva <notifications@github.com>
escreveu:

**Comment by crivano** [comment]
Mais um detalhe: existem N tipos diferentes de problemas e geral é um
deles. Claro que podemos substituir a string, mas como representaremos os
outros casos? Tipo: Problema - tnusinger... abs

Em sáb, 11 de jun de 2016 06:31, Renato Crivano <renato.crivano@gmail.com>
escreveu:

**Comment by crivano** [comment]
Troquei para essa mensagem aqui:

![captura_de_tela_062016_041252_pm](https://cloud.githubusercontent.com/assets/4137623/16207106/d8c4ff56-3701-11e6-9279-a5c93422c3d4.jpg)

**Comment by raphaelpaiva** [comment]
Muito bom! E a mensagem de quando o .exe está rodando, mas o token não está
espetado (que eu postei originalmente?

**Comment by crivano** [comment]
Tks. Corrigi a imagem acima.
