### ISSUE TITLE
Sistema para em "Listando documentos" no IE11

### ISSUE THREAD

**Issue by Markenson** [assijus/assijus#3]
Reportado por @andresousa17 que no IE11, algumas vezes, o sistema congelou com a barra de progresso indicando "LIstando documentos..." embora ele tenha confirmado com @raphaelpaiva que o servidor já havia retornado a resposta. 

Ao utilizar o Firefox, o erro não ocorreu na mesma máquina em que foi percebido o problema descrito.

**Comment by crivano** [comment]
Precisei substituir property.startsWith("status-") por property.indexOf("status-") == 0, pq o IE11 está numa versão mais antiga do JS.
