### ISSUE TITLE
Alterar página SOBRE

### ISSUE THREAD

**Issue by Markenson** [assijus/assijus#6]
Informado por Sheyla que

1.  a seguinte frase deve ser incluída na página SOBRE:

"No primeiro acesso ao Assijus, em cada equipamento, é necessária uma instalação prévia, conforme o Passo a passo abaixo: ou conforme as orientações abaixo"

2. retirar o item "quem pode utilizar?"

**Comment by crivano** [comment]
Alterei a página home para mostrar o passo a passo quando não encontrar o assijus.
