### ISSUE TITLE
Disponibilizar para download o arquivo .NET Framework

### ISSUE THREAD

**Issue by Markenson** [assijus/assijus#7]
Foi solicitado na reunião de 16/06/2016 que o arquivo de instalação do .NET Framework seja disponibilizado diretamente na página do assijus (juntamente com o link para o assijus.exe) em vez de apontar para o site da Microsoft.

**Comment by crivano** [comment]
@Markenson , vc chegou a pesquisar se isso é permitido pela Microsoft?

**Comment by crivano** [comment]
Copiei para dentro - 68MB! - e alterei o link.

**Comment by Markenson** [comment]
@crivano, não cheguei a pesquisar se é permitido.

**Comment by crivano** [comment]
@luizantonio e @raphaelpaiva , vocês aprovam que o tamanho do assijus.war suba de 3MB para 71MB só por conta desse download do .NET Framework independer de conexão de Internet?

**Comment by raphaelpaiva** [comment]
Crivano, não é melhor colocarmos em um apache nosso, por ser conteúdo
estático?

**Comment by crivano** [comment]
@raphaelpaiva , já fica no site da Microsoft. Por mim, teríamos apenas o link para lá. Se a internet estiver ruim, será difícil fazer assinaturas digitais pois a LCR não poderá ser atualizada. A questão é que colocar o download interno ficou decidido na última reunião. Bom, agora já está feito. Na próxima reunião podemos pedir que seja revisto... Obrigado.

**Comment by raphaelpaiva** [comment]
Um apache nosso seria interno. Se estiver sem internet, ainda seria
possível baixar pois estaria dentro da nossa rede. Dentro ou fora do war
não faz diferença pro download. O negócio é que o tamanho de deployment faz
diferença pro consumo de recursos e tempo de deploy. Um arquivo desse
tamanho não achamos razoável.

**Comment by crivano** [comment]
Ótimo, assim que o arquivo estiver em uma URL interna, por favor me avise que apontarei o link para lá. Obrigado.

**Comment by raphaelpaiva** [comment]
@crivano qual arquivo? Pode passar o link da microsoft?

**Comment by crivano** [comment]
https://download.microsoft.com/download/1/6/7/167F0D79-9317-48AE-AEDB-17120579F8E2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe

**Comment by raphaelpaiva** [comment]
http://assijus.jfrj.jus.br/downloads/Microsoft-DOT-NET-Framework-x86-x64-AllOS-ENU.exe
